### ISSUE TITLE
Doesnt work with twig files

### ISSUE THREAD

**Issue by ImKubass** [hossaini310/bootstrap-intellisense#1]
Hi,
I was trying this extension, it works with .html, but not with .twig files extension.
Is there any posibility to set what files extensions to work with?

**Comment by hossaini310** [comment]
Hello,
I have added twing to the `lenguageSupport' list, it should work now.

**Comment by ImKubass** [comment]
It works! Thanks
Maybe future feature to by be able to set whatever file extension you want
