### ISSUE TITLE
Autocompletion not working when using webjars

### ISSUE THREAD

**Issue by RafBel94** [hossaini310/bootstrap-intellisense#25]
First of all, sorry for the duplicated issue, there was something wrong with the first one.

Hello, I am using Java 23 with Spring, Spring Web, Thymeleaf, Webjars and Webjars-locator. The problem is that this extension is not autocompleting when using webjar, but if you put the link to the CDN, even if it is a commented code line, it works. Bootstrap works perfectly fine using CDN link or webjar, is just the autocompletion what does not work:

AUTOCOMPLETION NOT WORKING
![image](https://github.com/user-attachments/assets/f39c6a95-ce7c-4264-a12f-c0a319b83673)

WORKING EVEN WITH COMMENTED CODE
![image](https://github.com/user-attachments/assets/0b7a9c15-34cc-4f7e-84a4-40c47238f782)

**Comment by hossaini310** [comment]
webjar is now also supported and commented code is now ignored

**Comment by RafBel94** [comment]
Nice! Thanks and good work! :)
