### ISSUE TITLE
Add support for django-html

### ISSUE THREAD

**Issue by bigscorpions** [hossaini310/bootstrap-intellisense#3]
Would you mind to add `django-html` support just like erb files?

I have tried to add `django-html` to **extension.js** and it works.

In order to support django template file lint and format, the .html files in django templates folder will be associated with `django-html`:

```json
"files.associations": {
    "**/*.html": "html",
    "**/templates/**/*.html": "django-html"
  },
```

So bootstrap-intellisense will not work for .html files in django templates folder.

Thanks for the work!

**Comment by hossaini310** [comment]
I have now added `django-html` to languageSupport.

**Comment by bigscorpions** [comment]
Thanks for the work! It's really helpful! @hossaini310
