### ISSUE TITLE
blade laravel not working

### ISSUE THREAD

**Issue by ImBIOS** [hossaini310/bootstrap-intellisense#4]
![image](https://github.com/hossaini310/bootstrap-intellisense/assets/41441643/9771c9ad-e816-4613-a264-42e12b2c1bfd)

**Comment by hossaini310** [comment]
Press Ctrl + Spacebar
![image](https://github.com/hossaini310/bootstrap-intellisense/assets/76107069/bf7cd0fc-d984-44fd-bfab-2960c152fc9b)
