### ISSUE TITLE
Intellisense suggestions should appear in class attribute only

### ISSUE THREAD

**Issue by Maaz0313** [hossaini310/bootstrap-intellisense#9]
Please try that the Intellisense suggestions should appear in class attribute only.

**Comment by hossaini310** [comment]
Hello, what do you mean exactly? Can you give an example.

**Comment by Maaz0313** [comment]
When I first use intellisense and then try to add an html attribute after class attribute to the same html tag, it still shows suggestions.

**Comment by hossaini310** [comment]
Its now fixed
